The solution is made using list of Python. Here Numpy is used only to return the result as numpy array.

In [135]:
import numpy as np

In [284]:
global b 
b  = []
def find_soln(states):
    
    for items in states:
        assert len(items) == 5
        b.append(items)

    if len(b) < 3:
        return None
    elif len(b) == 3:
        result = [ele for ele in reversed(b)]
        return np.array(result)
    else:
        result = [ele for ele in reversed(b)]
        return np.array(result[:3])
    

In [285]:
a = find_soln([[1,2,3,4,5]])

In [286]:
print(a)

None


In [287]:
c = find_soln([[4,5,6,7,8]])

In [288]:
print(c)

None


In [289]:
d = find_soln([[0,3,5,2,1]])

In [290]:
print(d)

[[0 3 5 2 1]
 [4 5 6 7 8]
 [1 2 3 4 5]]


In [291]:
e = find_soln([[11,12,13,14,15]])

In [292]:
print(e)

[[11 12 13 14 15]
 [ 0  3  5  2  1]
 [ 4  5  6  7  8]]


In [293]:
f = find_soln([[2,3,4,0,0]])

In [294]:
print(f)

[[ 2  3  4  0  0]
 [11 12 13 14 15]
 [ 0  3  5  2  1]]
